# Generated by Django 2.1.1 on 2019-04-30 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('miasto', models.CharField(max_length=100)),
                ('wojewodztwo', models.CharField(max_length=100)),
                ('kodpocztowy', models.CharField(max_length=20)),
                ('opis', models.TextField(blank=True)),
                ('cena', models.IntegerField()),
                ('sypialnie', models.IntegerField()),
                ('lazienki', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garaz', models.IntegerField(default=0)),
                ('pow_domu', models.IntegerField()),
                ('pow_dzialki', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('zdjecie_glowne', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('zdjecie_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('zdjecie_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('zdjecie_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('zdjecie_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('zdjecie_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('zdjecie_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('czy_opublikowane', models.BooleanField(default=True)),
                ('data_oferty', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
