# Generated by Django 2.1.1 on 2019-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_oferty_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferty',
            name='lazienki',
            field=models.IntegerField(),
        ),
    ]
