# Generated by Django 2.1.1 on 2019-05-01 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.CharField(max_length=200)),
                ('oferta_id', models.IntegerField()),
                ('nazwa', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('wiadomosc', models.TextField(blank=True)),
                ('data_kontaktu', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('uzytkownik_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
