# Generated by Django 2.1.1 on 2019-05-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontakt',
            old_name='phone',
            new_name='telefon',
        ),
    ]
