# Generated by Django 2.1.1 on 2019-04-30 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190430_1612'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('zdjecie', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('opis', models.TextField(blank=True)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('czy_sprzedawcam', models.BooleanField(default=False)),
                ('data_zatrudnienia', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
